language: 
  - ruby

rvm:
  - 1.9.3

before_install:
  - sudo apt-get -y update -qq

install:
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install xorriso
  - sudo apt-get autoremove
  - sudo apt-get clean
  - sudo rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*

script:
  - wget -P test/res/ https://github.com/csc/Hanlon-Microkernel/releases/download/v2.0.0/hnl_mk_prod-image.2.0.0.iso
  - osirrox -indev test/res/hnl_mk_prod-image.2.0.0.iso -extract / hnl_mk_prod-image.2.0.0